### ISSUE TITLE
Page common layout

### ISSUE THREAD

**Issue by kuan0808** [DaJoX/GreenChase#3]
## Description

This is for the common layout throughout the site, reusable layout component.

## Folder Structure

```
project
└───ui
     └───Layout.jsx
```

## UI

- [x] Navbar (mobile responsive)
- [x] Sidebar (mobile responsive)

## Logics

- [x] Integrate Moralis login to Navbar wallet icon
- [x] Customize the style of the default theme of the wallet connection package to match the Sidebar design

**Comment by paschal533** [comment]
done
